FORMAT: 1A
HOST: https://api.github.com/v1

# API GitHub

## Sobre [/] 

Api de consulta de informações de usuarios teste do github

# Group Users

## User [/users]

### Endpoint de consulta de usuários [GET]

+ Response 200 (application/json)
    + Attributes (User)

# Data Structures

## User (object)
+ login (string) - Login do usuario
+ id (string) - id do usuário
+ name (string) - nome do usuario





